export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_DETAIL_MOVIE = "FETCH_DETAIL_MOVIE";
export const FETCH_SIMILAR_MOVIES = "FETCH_SIMILAR_MOVIES";
export const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES";
export const FETCH_GENRE_LIST_KEY = "FETCH_GENRE_LIST";
export const FETCH_SEARCH_MOVIES = "FETCH_SEARCH_MOVIES";


